Feature: Added organization auth
IEDCMEC/iedc-collab-frontend pull request #261
Opened 2023-12-24 15:31 UTC by subru-37

2023-12-24 15:38 UTC, jaison080 requested changes

2023-12-24 15:38 UTC, jaison080 commented on src/Components/FormSample/FormSample.jsx
Change the filename from FormSample to something which it is specific for or else debugging would be difficult for others.

2023-12-24 15:38 UTC, jaison080 commented on src/Components/InviteToProjectModal/InviteToProjectModal.js
Here only the mail function needs to be commented right.The invite functionality should work fine right?

2023-12-24 15:38 UTC, jaison080 commented on src/Components/JoinTeamModal/JoinTeamModal.js
Here only the mail function needs to be commented right.The request functionality should work fine right?

2023-12-24 15:38 UTC, jaison080 commented on src/Components/Request/Received.js
In these also the mail function only needs to be commented out right rest all are firebase functions right,

2023-12-24 16:39 UTC, subru-37 commented on src/Components/Request/Received.js
Yes, I will comment out the .then() part which handles the email function

2023-12-25 01:26 UTC, jaison080 approved these changes

2023-12-25 01:26 UTC, merged